version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-employment-exchange-web
    volumes: 
      - ".:/app"
    ports:
      - "8001:8000"
    tty: true