version: "3.9"

services:
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    env_file:
      - mysql.env
    ports:
      - "3307:3306"
    volumes:
      - "./mysql_volume:/var/lib/mysql"
    networks:
      employmentnetwork:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: symfony-employment-exchange-web
    volumes: 
      - ".:/app"
    restart: on-failure
    ports:
      - "8001:8000"
    tty: true
    depends_on: 
      - mysql
    links: 
      - mysql
    networks:
      employmentnetwork:
    
networks:
  employmentnetwork:
    driver: bridge