version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-employment-exchange-web
    volumes: 
      - ".:/app"
    ports:
      - "8001:8000"
    tty: true
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    env_file:
      - mysql.env
    ports:
      - "3307:3306"
    volumes:
      - "./mysql_volume:/var/lib/mysql"
    networks:
      usersnetwork:
networks:
  usersnetwork:
    driver: bridge