apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-08-29T00:33:49Z"
  generation: 1
  labels:
    app: symfony-employment-exchange-web
  name: symfony-employment-exchange-web
  namespace: default
  resourceVersion: "36287"
  selfLink: /apis/apps/v1/namespaces/default/deployments/symfony-employment-exchange-web
  uid: 6c2f8de1-b488-425d-8207-d32c33eab6e5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: symfony-employment-exchange-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: symfony-employment-exchange-web
    spec:
      containers:
      - image: caprilespe/symfony-employment-exchange-web:v1
        imagePullPolicy: IfNotPresent
        name: symfony-employment-exchange-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-29T00:34:34Z"
    lastUpdateTime: "2021-08-29T00:34:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-08-29T00:33:49Z"
    lastUpdateTime: "2021-08-29T00:34:34Z"
    message: ReplicaSet "symfony-employment-exchange-web-5f8c6d47f" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
