apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-08-29T00:36:21Z"
  labels:
    app: symfony-employment-exchange-web
  name: symfony-employment-exchange-web
  namespace: default
  resourceVersion: "36318"
  selfLink: /api/v1/namespaces/default/services/symfony-employment-exchange-web
  uid: 51ee90c2-778e-4e0a-bf69-78dd906295fb
spec:
  clusterIP: 10.106.230.235
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30407
    port: 8001
    protocol: TCP
    targetPort: 8000
  selector:
    app: symfony-employment-exchange-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
